import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@supabase/supabase-js";
import { obtenerClienteActual } from "@/lib/cliente-actual";
import { prisma } from "@/lib/prisma";
import { inspeccionLiberadaParaCliente } from "@/lib/portal-inspecciones";

function formatearFechaHora(fecha: Date, zonaHoraria: string) { return new Intl.DateTimeFormat("es-MX", { day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:zonaHoraria }).format(fecha); }
function obtenerSupabase(){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function crearUrlEvidencia(ruta:string){if(ruta.startsWith("http://")||ruta.startsWith("https://"))return ruta;const s=obtenerSupabase();if(!s)return null;const bucket=process.env.SUPABASE_STORAGE_BUCKET||"evidencias";const {data,error}=await s.storage.from(bucket).createSignedUrl(ruta,3600);if(error)return null;return data.signedUrl}

export default async function PortalInspeccionDetallePage({params}:{params:Promise<{id:string}>}){
 const cliente=await obtenerClienteActual();const {id}=await params;
 const inspeccion=await prisma.inspeccion.findFirst({where:{id,...inspeccionLiberadaParaCliente(cliente.id)},include:{inmueble:true,inspector:{include:{usuario:true}},hallazgos:{include:{fotografias:{orderBy:{creadaEn:"asc"}}},orderBy:[{prioridad:"asc"},{creadoEn:"asc"}]},fotografias:{where:{hallazgoId:null},orderBy:{creadaEn:"asc"}},firmas:{orderBy:{firmadaEn:"asc"}},certificado:true}});
 if(!inspeccion)notFound();
 const fotos=[...inspeccion.fotografias,...inspeccion.hallazgos.flatMap(h=>h.fotografias)];const urls=new Map<string,string>();await Promise.all(fotos.map(async f=>{const u=await crearUrlEvidencia(f.url);if(u)urls.set(f.id,u)}));
 const criticos=inspeccion.hallazgos.filter(h=>h.clasificacion==="CR").length;const nc=inspeccion.hallazgos.filter(h=>h.clasificacion==="NC").length;
 return <main className="mx-auto max-w-7xl px-6 py-10"><header><Link href="/portal/inspecciones" className="text-sm font-bold text-cyan-300">← Volver a mis inspecciones</Link><p className="mt-6 text-xs font-black uppercase tracking-[0.28em] text-emerald-300">Expediente liberado</p><h1 className="mt-2 text-4xl font-black">{inspeccion.folio}</h1><p className="mt-3 text-slate-400">{inspeccion.direccion}, {inspeccion.ciudad}</p></header>
 <section className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Resumen titulo="ISH" valor={inspeccion.ish!==null?Number(inspeccion.ish).toFixed(0):"—"}/><Resumen titulo="Hallazgos" valor={String(inspeccion.hallazgos.length)}/><Resumen titulo="No conformes" valor={String(nc)}/><Resumen titulo="Críticos" valor={String(criticos)}/></section>
 <section className="mt-8 grid gap-8 xl:grid-cols-[1fr_360px]"><div className="space-y-8"><article className="rounded-3xl border border-white/10 bg-slate-900 p-7"><h2 className="text-xl font-black">Información general</h2><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Dato label="Servicio" value={inspeccion.tipoServicio}/><Dato label="Inmueble" value={inspeccion.inmueble?.alias??inspeccion.tipoInmueble}/><Dato label="Inspector" value={inspeccion.inspector?.usuario.nombre??"—"}/><Dato label="Fecha" value={formatearFechaHora(inspeccion.fechaProgramada,inspeccion.zonaHoraria)}/></dl></article>
 <article className="overflow-hidden rounded-3xl border border-white/10 bg-slate-900"><header className="border-b border-white/10 p-7"><h2 className="text-xl font-black">Hallazgos técnicos</h2></header><div className="divide-y divide-white/10">{inspeccion.hallazgos.map((h,n)=><section key={h.id} className="p-7"><p className="text-xs font-black uppercase text-cyan-300">Hallazgo {n+1}</p><h3 className="mt-2 text-xl font-black">{h.titulo}</h3><p className="mt-1 text-sm text-slate-500">{h.area}{h.ubicacion?` · ${h.ubicacion}`:""}</p><p className="mt-5 whitespace-pre-line leading-7 text-slate-300">{h.descripcion}</p>{h.recomendacion&&<div className="mt-5 rounded-2xl bg-cyan-400/10 p-5"><p className="text-xs font-black uppercase text-cyan-300">Recomendación</p><p className="mt-3 text-cyan-100">{h.recomendacion}</p></div>}{h.fotografias.length>0&&<div className="mt-6 grid gap-4 sm:grid-cols-2">{h.fotografias.map(f=>{const u=urls.get(f.id);return u?<figure key={f.id} className="overflow-hidden rounded-2xl bg-slate-950"><img src={u} alt={f.descripcion??h.titulo} className="aspect-video w-full object-cover"/></figure>:null})}</div>}</section>)}</div></article></div>
 <aside><section className="rounded-3xl border border-emerald-300/20 bg-slate-900 p-7"><h2 className="text-xl font-black text-emerald-300">Certificado vigente</h2><p className="mt-5 text-xs uppercase text-slate-500">Folio</p><p className="mt-2 font-black text-cyan-300">{inspeccion.certificado?.folio}</p><p className="mt-5 text-xs uppercase text-slate-500">Código de validación</p><p className="mt-2 break-all font-black text-cyan-300">{inspeccion.certificado?.codigoValidacion}</p><p className="mt-5 text-sm text-slate-400">Este expediente solo es visible porque concluyó el flujo de cierre, aprobación y certificación.</p></section></aside></section></main>
}
function Resumen({titulo,valor}:{titulo:string;valor:string}){return <article className="rounded-3xl border border-white/10 bg-slate-900 p-6"><p className="text-xs font-black uppercase text-slate-500">{titulo}</p><p className="mt-3 text-3xl font-black text-cyan-300">{valor}</p></article>}
function Dato({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-950 p-4"><dt className="text-xs font-black uppercase text-slate-600">{label}</dt><dd className="mt-2 font-bold">{value}</dd></div>}
