import Link from "next/link";
import { EstadoCotizacion, RolUsuario } from "@prisma/client";
import { redirect } from "next/navigation";

import { obtenerUsuarioConAlcanceZona, puedeAccederZona } from "@/lib/alcance-zona";
import { calcularResumenFinancieroCaja } from "@/lib/caja-finanzas";
import { prisma } from "@/lib/prisma";
import { crearInspeccion } from "./actions";
import CotizacionSelect from "./CotizacionSelect";
import ZonaInspectorSelect from "./ZonaInspectorSelect";

type SearchParams=Promise<{error?:string;antecedenteId?:string}>;
export default async function NuevaInspeccionPage({searchParams}:{searchParams:SearchParams}){
  const usuarioActual=await obtenerUsuarioConAlcanceZona("/panel/inspecciones/nueva");
  if(![RolUsuario.DIRECTOR,RolUsuario.ADMINISTRADOR,RolUsuario.GERENTE].includes(usuarioActual.rol))redirect("/acceso");
  const params=await searchParams,antecedenteId=params.antecedenteId?.trim()||"";
  const antecedente=antecedenteId?await prisma.inspeccion.findUnique({where:{id:antecedenteId},select:{id:true,folio:true,estado:true,clienteId:true,inmuebleId:true,inspectorId:true,plantillaId:true,zonaId:true,numeroInspeccion:true,cliente:{select:{nombre:true}},inmueble:{select:{alias:true,direccion:true}}}}):null;
  if(antecedenteId&&!antecedente)redirect(`/panel/inspecciones/nueva?error=${encodeURIComponent("La inspección antecedente no existe.")}`);
  if(antecedente&&!puedeAccederZona(usuarioActual,antecedente.zonaId))redirect("/acceso");

  const zonaObligatoria=usuarioActual.rol===RolUsuario.DIRECTOR?(antecedente?.zonaId??null):usuarioActual.zonaId;
  const [cotizacionesBase,inspectores,zonas,plantillas]=await Promise.all([
    prisma.cotizacion.findMany({where:{estado:EstadoCotizacion.AUTORIZADA,inmuebleId:{not:null},inspeccion:null,...(zonaObligatoria?{zonaId:zonaObligatoria}:{}),...(antecedente?{clienteId:antecedente.clienteId,inmuebleId:antecedente.inmuebleId}:{})},select:{id:true,folio:true,clienteId:true,inmuebleId:true,zonaId:true,total:true,montoPagado:true,excepcionApertura:true,excepcionInicio:true,cliente:{select:{nombre:true}},inmueble:{select:{alias:true}}},orderBy:{autorizadaEn:"desc"}}),
    prisma.inspector.findMany({where:{activo:true,usuario:{activo:true,rol:RolUsuario.INSPECTOR,...(zonaObligatoria?{zonaId:zonaObligatoria}:{})}},select:{id:true,usuario:{select:{nombre:true,zonaId:true,gerenteId:true,coordinadorId:true}}},orderBy:{creadoEn:"asc"}}),
    prisma.zona.findMany({where:{activa:true,...(usuarioActual.rol===RolUsuario.DIRECTOR?{}:{id:usuarioActual.zonaId!})},select:{id:true,nombre:true,codigo:true},orderBy:{nombre:"asc"}}),
    prisma.plantillaInspeccion.findMany({where:{activa:true},orderBy:{nombre:"asc"}}),
  ]);
  const cotizaciones=cotizacionesBase.map(c=>({c,resumen:calcularResumenFinancieroCaja({importe:Number(c.total),pagado:Number(c.montoPagado),excepcionApertura:c.excepcionApertura,excepcionInicio:c.excepcionInicio,tieneInspeccion:false,fechaAgendada:null})})).filter(x=>x.resumen.puedeAgendar).map(({c,resumen})=>({id:c.id,folio:c.folio,clienteId:c.clienteId,clienteNombre:c.cliente.nombre,inmuebleId:c.inmuebleId!,inmuebleAlias:c.inmueble?.alias??"Inmueble",total:resumen.importe,montoPagado:resumen.pagado,excepcionApertura:c.excepcionApertura}));
  return <main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><div className="mx-auto max-w-5xl"><div className="flex justify-between gap-4"><Link href="/panel/inspecciones" className="text-sm font-black text-cyan-300">← Inspecciones</Link>{[RolUsuario.DIRECTOR,RolUsuario.ADMINISTRADOR].includes(usuarioActual.rol)&&<Link href="/panel/configuracion/plantillas" className="text-sm font-black text-amber-300">Configurar plantillas</Link>}</div><p className="mt-7 text-xs font-black uppercase tracking-[0.3em] text-amber-300">Operación comercial vinculada</p><h1 className="mt-3 text-4xl font-black">{antecedente?`Nueva inspección V${antecedente.numeroInspeccion+1}`:"Nueva inspección V1"}</h1><p className="mt-3 text-slate-400">{usuarioActual.rol===RolUsuario.DIRECTOR?"Dirección puede programar en cualquier zona; cotización, zona e inspector deben coincidir.":`Solo puedes crear inspecciones en ${usuarioActual.zona?.nombre??"tu zona"}.`}</p>{params.error&&<div className="mt-6 rounded-2xl border border-rose-400/20 p-4 text-rose-200">{params.error}</div>}
  <form action={crearInspeccion} className="mt-8 space-y-6 rounded-3xl border border-white/10 bg-slate-900 p-7">{antecedente&&<><input type="hidden" name="antecedenteId" value={antecedente.id}/><div className="grid gap-4 rounded-2xl border border-cyan-300/20 p-5 md:grid-cols-2"><Dato label="Antecedente" value={`V${antecedente.numeroInspeccion} · ${antecedente.folio}`}/><Dato label="Cliente" value={antecedente.cliente.nombre}/><Dato label="Inmueble" value={antecedente.inmueble?.alias??"Inmueble"}/><Dato label="Dirección" value={antecedente.inmueble?.direccion??"—"}/></div></>}{cotizaciones.length?<CotizacionSelect cotizaciones={cotizaciones}/>:<div className="rounded-2xl border border-amber-300/20 p-5 text-amber-200">No hay cotizaciones autorizadas y financieramente habilitadas dentro de la zona permitida.</div>}<CampoSelect name="plantillaId" label="Plantilla de inspección *" required defaultValue={antecedente?.plantillaId??""} options={plantillas.map(p=>({value:p.id,label:`${p.nombre} · Gerente: ${p.requiereGerenteZona?"Sí":"No"} · Coordinador: ${p.requiereCoordinador?"Sí":"No"}`}))}/><ZonaInspectorSelect zonas={zonas} inspectores={inspectores} zonaInicial={antecedente?.zonaId??usuarioActual.zonaId??""} inspectorInicial={antecedente?.inspectorId??""}/><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Fecha y hora *</span><input name="fechaProgramada" type="datetime-local" required className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3"/></label><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Observaciones</span><textarea name="observaciones" rows={4} className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3"/></label><button type="submit" disabled={!cotizaciones.length} className="w-full rounded-full bg-cyan-400 px-6 py-3 font-black text-slate-950 disabled:opacity-40">Crear y programar {antecedente?`V${antecedente.numeroInspeccion+1}`:"V1"}</button></form></div></main>;
}
function CampoSelect({name,label,options,required=false,defaultValue=""}:{name:string;label:string;options:{value:string;label:string}[];required?:boolean;defaultValue?:string}){return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">{label}</span><select name={name} required={required} defaultValue={defaultValue} className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3">{!defaultValue&&<option value="">Selecciona una opción</option>}{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
function Dato({label,value}:{label:string;value:string}){return <div><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>;}
