import Link from "next/link";
import { EstadoInspeccion, RolUsuario } from "@prisma/client";
import { redirect } from "next/navigation";
import { obtenerUsuarioConAlcanceZona, zonaEfectivaId } from "@/lib/alcance-zona";
import { prisma } from "@/lib/prisma";
import { actualizarAgenda } from "./actions";

function fecha(valor: Date, zona: string) { return new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short", timeZone: zona }).format(valor); }
function fechaInput(valor: Date) { const d = new Date(valor.getTime() - valor.getTimezoneOffset() * 60000); return d.toISOString().slice(0,16); }
function estatusAgenda(estado: EstadoInspeccion) { return estado.replaceAll("_"," "); }

export default async function AgendaPage({ searchParams }: { searchParams: Promise<{ q?: string; estado?: string; vista?: string; zonaId?: string; ok?: string; error?: string }> }) {
  const usuario=await obtenerUsuarioConAlcanceZona("/panel/agenda");
  if(usuario.rol===RolUsuario.CLIENTE) redirect("/acceso");
  const roles=[RolUsuario.DIRECTOR,RolUsuario.ADMINISTRADOR,RolUsuario.VENDEDOR,RolUsuario.GERENTE,RolUsuario.COORDINADOR,RolUsuario.INSPECTOR]; if(!roles.includes(usuario.rol)) redirect("/acceso");
  const p=await searchParams,q=(p.q??"").trim(),filtro=(p.estado??"").trim(),historico=p.vista==="canceladas";
  const zonaId=zonaEfectivaId(usuario,p.zonaId);
  const zonas=usuario.rol===RolUsuario.DIRECTOR?await prisma.zona.findMany({where:{activa:true},select:{id:true,nombre:true,codigo:true},orderBy:{nombre:"asc"}}):[];
  let alcance:Record<string,unknown>={};
  if(usuario.rol===RolUsuario.INSPECTOR){if(!usuario.inspector?.id) redirect("/acceso"); alcance={inspectorId:usuario.inspector.id};}
  else if(usuario.rol===RolUsuario.GERENTE) alcance={inspector:{usuario:{gerenteId:usuario.id}}};
  else if(usuario.rol===RolUsuario.COORDINADOR) alcance={inspector:{usuario:{coordinadorId:usuario.id}}};
  const gestiona=usuario.rol===RolUsuario.DIRECTOR||usuario.rol===RolUsuario.ADMINISTRADOR;
  const estados=historico?[EstadoInspeccion.CANCELADA]:[EstadoInspeccion.PROGRAMADA,EstadoInspeccion.EN_PROCESO,EstadoInspeccion.FINALIZADA];
  const inspecciones=await prisma.inspeccion.findMany({where:{...alcance,...(zonaId?{zonaId}:{}),estado:{in:estados},...(q?{OR:[{folio:{contains:q,mode:"insensitive"}},{cliente:{nombre:{contains:q,mode:"insensitive"}}},{inmueble:{alias:{contains:q,mode:"insensitive"}}},{direccion:{contains:q,mode:"insensitive"}},{cotizacion:{folio:{contains:q,mode:"insensitive"}}}]}:{})},select:{id:true,folio:true,fechaProgramada:true,estado:true,direccion:true,zonaHoraria:true,cliente:{select:{nombre:true}},inmueble:{select:{alias:true}},cotizacion:{select:{folio:true}},zona:{select:{nombre:true,codigo:true,zonaHoraria:true}}},orderBy:[{fechaProgramada:"desc"},{folio:"desc"}],take:500});
  const filas=inspecciones.filter(i=>historico||!filtro||i.estado===filtro);
  const zonaQuery=usuario.rol===RolUsuario.DIRECTOR&&p.zonaId?`&zonaId=${encodeURIComponent(p.zonaId)}`:"";
  return <main className="min-h-screen bg-slate-950 px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-[1700px]">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-black uppercase tracking-[0.28em] text-amber-300">Operación</p><h1 className="mt-2 text-4xl font-black">Agenda</h1><p className="mt-3 text-slate-400">{usuario.rol===RolUsuario.DIRECTOR?"Dirección consulta todas las agendas separadas por zona.":`Agenda limitada a ${usuario.zona?.nombre??"tu zona"} y a tu jerarquía.`}</p><div className="mt-4 flex gap-2"><Link href={`/panel/agenda?vista=activas${zonaQuery}`} className={`rounded-full px-4 py-2 text-sm font-black ${!historico?"bg-cyan-300 text-slate-950":"border border-white/15"}`}>Agenda activa</Link><Link href={`/panel/agenda?vista=canceladas${zonaQuery}`} className={`rounded-full px-4 py-2 text-sm font-black ${historico?"bg-rose-300 text-slate-950":"border border-white/15"}`}>Histórico canceladas</Link></div></div>
    <form className="grid gap-2 sm:grid-cols-[minmax(250px,1fr)_190px_220px_auto]"><input type="hidden" name="vista" value={historico?"canceladas":"activas"}/><input name="q" defaultValue={q} placeholder="Buscar inspección, cotización, cliente o inmueble" className="rounded-full border border-white/10 bg-slate-900 px-5 py-3"/>{!historico?<select name="estado" defaultValue={filtro} className="rounded-full border border-white/10 bg-slate-900 px-5"><option value="">Todos los estatus</option><option value="PROGRAMADA">Programada</option><option value="EN_PROCESO">En proceso</option><option value="FINALIZADA">Finalizada</option></select>:<div className="rounded-full border border-white/10 px-5 py-3 text-slate-400">CANCELADA</div>}{usuario.rol===RolUsuario.DIRECTOR?<select name="zonaId" defaultValue={p.zonaId??""} className="rounded-full border border-white/10 bg-slate-900 px-5"><option value="">Todas las zonas</option>{zonas.map(z=><option key={z.id} value={z.id}>{z.nombre} · {z.codigo}</option>)}</select>:<div className="rounded-full border border-cyan-300/20 px-5 py-3 text-cyan-200">{usuario.zona?.nombre}</div>}<button className="rounded-full border border-white/15 px-5 font-black">Filtrar</button></form></div>
    {(p.ok||p.error)&&<p className={`mt-6 rounded-2xl border p-4 font-bold ${p.error?"border-rose-400/20 text-rose-300":"border-emerald-400/20 text-emerald-300"}`}>{p.error??p.ok}</p>}
    <div className="mt-8 overflow-x-auto rounded-3xl border border-white/10 bg-slate-900/70"><table className="min-w-[1650px] w-full text-left"><thead className="sticky top-0 bg-slate-900"><tr className="text-[10px] font-black uppercase text-slate-400"><th className="p-4">Inspección</th><th className="p-4">Cotización</th><th className="p-4">Cliente</th><th className="p-4">Inmueble</th><th className="p-4">Zona</th><th className="p-4">Domicilio</th><th className="p-4">Fecha</th><th className="p-4">Estatus</th></tr></thead><tbody>{filas.map(i=>{const zh=i.zona?.zonaHoraria??i.zonaHoraria??"America/Ciudad_Juarez";return <tr key={i.id} className="border-t border-white/5 align-top"><td className="p-4 font-mono text-xs font-black text-cyan-300">{i.folio}</td><td className="p-4 font-mono text-xs">{i.cotizacion?.folio??"—"}</td><td className="p-4 font-bold">{i.cliente.nombre}</td><td className="p-4">{i.inmueble?.alias??"—"}</td><td className="p-4">{i.zona?`${i.zona.nombre} · ${i.zona.codigo}`:"—"}</td><td className="p-4">{i.direccion}</td><td className="p-4">{!historico&&gestiona?<form action={actualizarAgenda} className="flex min-w-[430px] gap-2"><input type="hidden" name="inspeccionId" value={i.id}/><input type="datetime-local" name="fechaProgramada" defaultValue={fechaInput(i.fechaProgramada)} required className="rounded-xl bg-slate-950 px-3 py-2 text-xs"/><select name="estado" defaultValue={i.estado} className="rounded-xl bg-slate-950 px-3 py-2 text-xs"><option value="PROGRAMADA">PROGRAMADA</option><option value="EN_PROCESO">EN PROCESO</option><option value="FINALIZADA">FINALIZADA</option></select><button className="rounded-xl bg-cyan-300 px-3 py-2 text-xs font-black text-slate-950">Guardar</button></form>:fecha(i.fechaProgramada,zh)}</td><td className="p-4">{estatusAgenda(i.estado)}</td></tr>})}</tbody></table>{filas.length===0&&<div className="p-10 text-center text-slate-400">Sin registros dentro de la zona seleccionada.</div>}</div>
  </div></main>;
}
