import Link from "next/link";
import { EstadoCotizacion, Prisma } from "@prisma/client";
import { notFound } from "next/navigation";
import { obtenerClienteActual } from "@/lib/cliente-actual";
import { DATOS_DOCUMENTALES, datosContactoDocumento } from "@/lib/datos-documentales";
import { prisma } from "@/lib/prisma";
import PrintButton from "./PrintButton";
type Props={params:Promise<{id:string}>}; type Obj=Record<string,unknown>;
function dinero(v:unknown){return new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",minimumFractionDigits:2}).format(Number(v??0));}
function fecha(v:Date|null|undefined){return v?new Intl.DateTimeFormat("es-MX",{day:"2-digit",month:"long",year:"numeric"}).format(v):"—";}
function obj(v:Prisma.JsonValue|undefined):Obj|null{return v&&typeof v==="object"&&!Array.isArray(v)?v as Obj:null;}
function txt(v:unknown,f=""){return typeof v==="string"&&v.trim()?v.trim():f;}
function num(v:unknown,f:unknown){const n=Number(v);return Number.isFinite(n)?n:Number(f??0);}
export default async function CotizacionImprimirPage({params}:Props){
 const clienteActual=await obtenerClienteActual(); const {id}=await params;
 const c=await prisma.cotizacion.findFirst({where:{id,clienteId:clienteActual.id,zonaId:clienteActual.zonaId},include:{cliente:true,inmueble:true,paquete:true,creadaPor:{select:{nombre:true}},versiones:{orderBy:{version:"desc"},take:1,select:{version:true,datos:true,total:true,creadaEn:true}}}});
 const estadosVisibles:EstadoCotizacion[]=[EstadoCotizacion.ENVIADA,EstadoCotizacion.ACEPTADA,EstadoCotizacion.RECHAZADA];
 if(!c||!estadosVisibles.includes(c.estado))notFound(); const version=c.versiones[0]; if(!version||version.version!==c.versionActual)notFound();
 const datos=obj(version.datos),cli=obj(datos?.cliente as Prisma.JsonValue|undefined),inm=obj(datos?.inmueble as Prisma.JsonValue|undefined); const nombre=txt(cli?.nombre,c.cliente.nombre),alias=txt(inm?.alias,c.inmueble?.alias??"Sin inmueble asociado"),direccion=txt(inm?.direccion,c.inmueble?.direccion??""),colonia=txt(inm?.colonia,c.inmueble?.colonia??""),ciudad=txt(inm?.ciudad,c.inmueble?.ciudad??""),estado=txt(inm?.estado,c.inmueble?.estado??""),cp=txt(inm?.codigoPostal,c.inmueble?.codigoPostal??""); const direccionCompleta=[direccion,colonia,ciudad,estado,cp?`C.P. ${cp}`:""].filter(Boolean).join(", "); const m2=num(inm?.m2Construccion,c.superficieM2),terreno=num(inm?.m2Terreno,c.inmueble?.superficieTerrenoM2),total=num(datos?.total,version.total??c.total),contacto=datosContactoDocumento();
 return <main className="min-h-screen bg-slate-200 px-4 py-8 text-slate-950 print:bg-white print:p-0"><style>{`@page{size:Letter;margin:12mm}@media print{.no-imprimir{display:none!important}body{background:white!important}}`}</style><div className="no-imprimir mx-auto mb-5 flex max-w-[215.9mm] justify-between"><Link href={`/portal/cotizaciones/${c.id}`} className="font-bold">← Volver</Link><PrintButton/></div><article className="mx-auto max-w-[215.9mm] bg-white p-10 shadow-2xl print:shadow-none">
 <header className="flex items-start justify-between gap-6 border-b-4 border-slate-950 pb-6"><div className="flex items-center gap-4"><img src={DATOS_DOCUMENTALES.logo} alt="Certeza Habitacional" className="h-16 w-auto"/><div><p className="font-black uppercase tracking-wider">{DATOS_DOCUMENTALES.empresa}</p><p className="mt-1 text-xs text-slate-500">{DATOS_DOCUMENTALES.eslogan}</p></div></div><div className="text-right"><p className="text-xs font-black uppercase text-cyan-700">Cotización oficial · V{version.version}</p><p className="mt-2 font-mono font-black">{c.folio}</p></div></header>
 <section className="mt-8 rounded-3xl bg-slate-950 p-8 text-white"><p className="text-xs font-black uppercase tracking-[.25em] text-amber-300">Propuesta de servicios</p><h1 className="mt-3 text-4xl font-black">Inspección profesional de vivienda</h1><div className="mt-7 grid gap-4 sm:grid-cols-2"><Dato l="Cliente" v={nombre}/><Dato l="Inmueble" v={alias}/><Dato l="Dirección" v={direccionCompleta||"No registrada"}/><Dato l="Superficie construcción" v={`${m2.toLocaleString("es-MX")} m²`}/><Dato l="Superficie terreno" v={`${terreno.toLocaleString("es-MX")} m²`}/><Dato l="Servicio" v={c.paquete?.nombre??"Servicio de inspección"}/></div></section>
 <section className="mt-7 grid gap-5 sm:grid-cols-3"><DatoClaro l="Versión" v={`V${version.version}`}/><DatoClaro l="Vigencia" v={fecha(c.vigenciaHasta)}/><DatoClaro l="Estado" v={c.estado.replaceAll("_"," ")}/></section><section className="mt-7 rounded-3xl border-2 border-slate-950 p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-slate-500">Total cotizado · V{version.version}</p><p className="mt-2 text-sm text-slate-500">Importe del snapshot documental vigente.</p></div><p className="text-4xl font-black">{dinero(total)}</p></div></section>
 <section className="mt-7"><h2 className="text-lg font-black">Condición de aceptación</h2><p className="mt-3 text-sm leading-6 text-slate-600">Este documento reproduce la versión V{version.version} disponible en el portal. La aceptación electrónica queda vinculada exclusivamente a esta versión. Cualquier corrección posterior genera una nueva versión que debe revisarse y aceptarse nuevamente.</p></section>{c.notas&&<section className="mt-7"><h2 className="text-lg font-black">Notas</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{c.notas}</p></section>}
 <footer className="mt-10 border-t pt-5 text-xs text-slate-500"><div className="flex justify-between gap-6"><div><p className="font-black text-slate-900">{DATOS_DOCUMENTALES.empresa}</p>{contacto.map(x=><p key={x} className="mt-1">{x}</p>)}</div><div className="text-right"><p>Folio {c.folio} · V{version.version}</p><p className="mt-1">Generada: {fecha(version.creadaEn)}</p><p className="mt-1">Elaboró: {c.creadaPor?.nombre??DATOS_DOCUMENTALES.empresa}</p></div></div></footer></article></main>;
}
function Dato({l,v}:{l:string;v:string}){return <div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{l}</p><p className="mt-1 font-bold">{v}</p></div>}
function DatoClaro({l,v}:{l:string;v:string}){return <div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">{l}</p><p className="mt-1 font-black">{v}</p></div>}
