import Link from "next/link";
import { EstadoCotizacion, RolUsuario } from "@prisma/client";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { aceptarEnRepresentacionDelCliente, autorizarCotizacionAceptada, marcarListaParaCliente } from "./actions-flujo-aprobado";

function dinero(v: unknown) { return new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", minimumFractionDigits: 2 }).format(Number(v ?? 0)); }
function fecha(v: Date | null) { return v ? new Intl.DateTimeFormat("es-MX", { day: "2-digit", month: "2-digit", year: "numeric" }).format(v) : "—"; }

export default async function CotizacionesPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string; q?: string }> }) {
 const session = await auth(); if (!session?.user?.id) redirect("/login");
 const u = await prisma.usuario.findUnique({ where:{id:session.user.id}, select:{rol:true,activo:true} });
 if (!u?.activo || ![RolUsuario.DIRECTOR,RolUsuario.ADMINISTRADOR,RolUsuario.VENDEDOR].includes(u.rol)) redirect("/acceso");
 const p=await searchParams, q=(p.q??"").trim(), gestiona=u.rol===RolUsuario.DIRECTOR||u.rol===RolUsuario.ADMINISTRADOR;
 const cs=await prisma.cotizacion.findMany({where:q?{OR:[{folio:{contains:q,mode:"insensitive"}},{cliente:{nombre:{contains:q,mode:"insensitive"}}},{inmueble:{alias:{contains:q,mode:"insensitive"}}}]}:undefined,select:{id:true,folio:true,estado:true,total:true,montoPagado:true,creadoEn:true,vigenciaHasta:true,aceptadaEn:true,autorizadaEn:true,observacionesInternas:true,cliente:{select:{nombre:true,usuarioId:true}},inmueble:{select:{alias:true,direccion:true,ciudad:true}},inspeccion:{select:{id:true,folio:true,numeroInspeccion:true}}},orderBy:{creadoEn:"desc"}});
 const pc=cs.filter(c=>c.estado===EstadoCotizacion.ENVIADA).length, pa=cs.filter(c=>c.estado===EstadoCotizacion.ACEPTADA).length, az=cs.filter(c=>c.estado===EstadoCotizacion.AUTORIZADA).length;
 return <main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Link href="/panel" className="text-sm font-black text-cyan-300">← Volver al panel</Link><p className="mt-7 text-sm font-black uppercase tracking-[0.3em] text-amber-300">Flujo comercial aprobado</p><h1 className="mt-3 text-4xl font-black">Cotizaciones</h1><p className="mt-3 max-w-3xl text-slate-400">Cotización definitiva → aceptación del cliente → autorización interna → Caja.</p></div><div className="flex flex-wrap gap-3">{gestiona&&<Link href="/panel/cotizaciones/carga" className="rounded-full bg-cyan-300 px-5 py-3 text-sm font-black text-slate-950">Cargar PDF definitivo</Link>}{gestiona&&<Link href="/panel/clientes/accesos" className="rounded-full border border-white/15 px-5 py-3 text-sm font-black">Acceso clientes</Link>}{gestiona&&<Link href="/panel/caja" className="rounded-full border border-white/15 px-5 py-3 text-sm font-black">Caja</Link>}</div></div>
  {(p.ok||p.error)&&<div className={`mt-7 rounded-2xl border p-5 ${p.error?"border-rose-400/20 bg-rose-400/5":"border-emerald-400/20 bg-emerald-400/5"}`}><p className={`font-bold ${p.error?"text-rose-300":"text-emerald-300"}`}>{p.error??p.ok}</p></div>}
  <section className="mt-8 grid gap-4 sm:grid-cols-3"><Indicador t="Pendientes del cliente" v={pc} d="Listas para aceptar"/><Indicador t="Pendientes de autorización" v={pa} d="Ya aceptadas"/><Indicador t="En Caja" v={az} d="Aceptadas y autorizadas"/></section>
  <form className="mt-8 flex max-w-2xl gap-2"><input name="q" defaultValue={q} placeholder="Buscar folio, cliente o inmueble" className="min-w-0 flex-1 rounded-full border border-white/10 bg-slate-900 px-5 py-3"/><button className="rounded-full border border-white/15 px-5 py-3 font-black">Filtrar</button></form>
  {gestiona&&<div className="mt-8 rounded-3xl border border-cyan-300/20 bg-cyan-300/5 p-6"><p className="font-black text-cyan-300">Incorporación formal</p><p className="mt-2 text-sm text-slate-300">La pre-cotización pública no se modifica. El PDF definitivo sin marca PRE COTIZACIÓN se incorpora aquí y queda vinculado a Cliente e Inmueble.</p></div>}
  <section className="mt-8 space-y-5">{cs.map(c=>{const total=Number(c.total),pagado=Number(c.montoPagado);return <article key={c.id} className="rounded-3xl border border-white/10 bg-slate-900 p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex flex-wrap items-center gap-3"><p className="font-mono text-xs font-black text-cyan-300">{c.folio}</p><Estado e={c.estado}/></div><h2 className="mt-3 text-2xl font-black">{c.cliente.nombre}</h2><p className="mt-2 text-sm text-slate-400">{c.inmueble?`${c.inmueble.alias} · ${c.inmueble.direccion}, ${c.inmueble.ciudad}`:"Sin inmueble asociado"}</p><div className="mt-4 grid gap-3 text-sm text-slate-400 sm:grid-cols-2 lg:grid-cols-4"><p>Creada: <b className="text-slate-200">{fecha(c.creadoEn)}</b></p><p>Aceptada: <b className="text-slate-200">{fecha(c.aceptadaEn)}</b></p><p>Autorizada: <b className="text-slate-200">{fecha(c.autorizadaEn)}</b></p><p>Vigencia: <b className="text-slate-200">{fecha(c.vigenciaHasta)}</b></p></div></div><div className="lg:text-right"><p className="text-xs font-black uppercase tracking-widest text-slate-500">Importe</p><p className="mt-1 text-3xl font-black text-cyan-300">{dinero(total)}</p><p className="mt-2 text-sm text-slate-400">Pagado {dinero(pagado)} · Saldo {dinero(Math.max(0,total-pagado))}</p></div></div>
  {c.observacionesInternas&&<div className="mt-5 rounded-2xl border border-amber-300/10 bg-amber-300/5 p-4 text-sm text-slate-300">{c.observacionesInternas}</div>}
  {gestiona&&<div className="mt-6 border-t border-white/10 pt-5">{c.estado===EstadoCotizacion.BORRADOR&&(!c.cliente.usuarioId?<Link href="/panel/clientes/accesos" className="rounded-full bg-amber-300 px-5 py-3 text-sm font-black text-slate-950">Asignar acceso al cliente</Link>:<form action={marcarListaParaCliente}><input type="hidden" name="id" value={c.id}/><button className="rounded-full bg-cyan-300 px-5 py-3 text-sm font-black text-slate-950">Poner a aceptación del cliente</button></form>)}{c.estado===EstadoCotizacion.ENVIADA&&<div className="space-y-4"><p className="font-black text-cyan-300">Pendiente de aceptación del cliente.</p><form action={aceptarEnRepresentacionDelCliente} className="flex flex-col gap-3 md:flex-row"><input type="hidden" name="id" value={c.id}/><input name="motivo" required placeholder="Motivo excepcional" className="min-w-0 flex-1 rounded-xl bg-slate-950 px-4 py-3"/><button className="rounded-xl border border-amber-300/30 px-5 py-3 font-black text-amber-300">Aceptar en representación</button></form></div>}{c.estado===EstadoCotizacion.ACEPTADA&&<div className="flex flex-wrap items-center gap-3"><p className="font-black text-emerald-300">Aceptada. Pendiente de autorización interna.</p><form action={autorizarCotizacionAceptada}><input type="hidden" name="id" value={c.id}/><button className="rounded-full bg-emerald-300 px-5 py-3 text-sm font-black text-slate-950">Autorizar y enviar a Caja</button></form></div>}{c.estado===EstadoCotizacion.AUTORIZADA&&<div className="flex flex-wrap gap-3"><Link href="/panel/caja" className="rounded-full border border-violet-300/30 px-5 py-3 text-sm font-black text-violet-300">Abrir Caja</Link>{c.inspeccion&&<Link href={`/panel/inspecciones/${c.inspeccion.id}`} className="rounded-full border border-white/15 px-5 py-3 text-sm font-black">Ver V{c.inspeccion.numeroInspeccion}</Link>}</div>}</div>}{u.rol===RolUsuario.VENDEDOR&&<div className="mt-6 rounded-2xl border border-white/10 p-4 text-sm text-slate-400">Consulta únicamente.</div>}</article>})}{!cs.length&&<div className="rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-400">No hay cotizaciones con ese filtro.</div>}</section>
 </div></main>;
}
function Indicador({t,v,d}:{t:string;v:number;d:string}){return <article className="rounded-3xl border border-white/10 bg-slate-900 p-6"><p className="text-sm font-bold text-slate-400">{t}</p><p className="mt-4 text-3xl font-black text-cyan-300">{String(v).padStart(2,"0")}</p><p className="mt-2 text-xs text-slate-600">{d}</p></article>}
function Estado({e}:{e:EstadoCotizacion}){const c=e===EstadoCotizacion.AUTORIZADA?"text-violet-300 bg-violet-400/10":e===EstadoCotizacion.ACEPTADA?"text-emerald-300 bg-emerald-400/10":e===EstadoCotizacion.ENVIADA?"text-cyan-300 bg-cyan-400/10":e===EstadoCotizacion.RECHAZADA||e===EstadoCotizacion.CANCELADA?"text-rose-300 bg-rose-400/10":"text-slate-300 bg-slate-400/10";return <span className={`rounded-full px-3 py-1 text-xs font-black ${c}`}>{e.replaceAll("_"," ")}</span>}
