"use server";

import { randomUUID } from "node:crypto";
import { RolUsuario, TipoEvento } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { registrarAuditoria } from "@/lib/auditoria";
import { prisma } from "@/lib/prisma";
import { supabaseAdmin } from "@/lib/supabase-admin";

const TIPOS = new Set(["ARQUITECTONICO","FACHADAS","HIDRAULICA","SANITARIA","GAS","ELECTRICA","PUERTAS_VENTANAS","ACABADOS","AIRE_ACONDICIONADO","VOZ_DATOS","OTROS"]);
const BASE: Record<string,string[]> = {
 ARQUITECTONICO:["Distribución y correspondencia de espacios","Dimensiones y circulaciones","Muros, vanos y niveles"], FACHADAS:["Correspondencia de fachadas","Alineamientos, desplomes y remates","Sellos y encuentros exteriores"], HIDRAULICA:["Alimentación y distribución de agua","Válvulas, conexiones y fugas","Presión y funcionamiento de muebles"], SANITARIA:["Descargas y pendientes","Registros y ventilaciones","Pruebas de funcionamiento y fugas"], GAS:["Tuberías, válvulas y conexiones","Ubicación y ventilación","Prueba de hermeticidad aplicable"], ELECTRICA:["Tablero, protecciones y circuitos","Contactos, apagadores y polaridad","Canalizaciones y puesta a tierra"], PUERTAS_VENTANAS:["Alineación, plomo y nivel","Apertura, cierre y herrajes","Sellos, vidrios y acabados"], ACABADOS:["Pisos y piezas huecas","Muros, plafones y pintura","Juntas, boquillas y remates"], AIRE_ACONDICIONADO:["Equipos y ubicación","Drenajes y alimentación","Operación y distribución"], VOZ_DATOS:["Salidas y canalizaciones","Ubicación contra proyecto","Identificación y terminaciones"], OTROS:["Conceptos particulares del proyecto"]
};
function t(fd:FormData,k:string){return String(fd.get(k)??"").trim()}
function volver(id:string,tipo:"ok"|"error",m:string):never{redirect(`/panel/inspecciones/${id}/preparacion?${tipo}=${encodeURIComponent(m)}`)}
async function actor(){const s=await auth();if(!s?.user?.id)redirect("/login");const u=await prisma.usuario.findUnique({where:{id:s.user.id},select:{id:true,rol:true,activo:true}});if(!u?.activo||![RolUsuario.DIRECTOR,RolUsuario.ADMINISTRADOR,RolUsuario.GERENTE].includes(u.rol as never))redirect("/acceso");return u}
async function tablas(){const r=await prisma.$queryRaw<Array<{d:string|null;g:string|null}>>`SELECT to_regclass('public."DocumentoProyectoInspeccion"')::text d,to_regclass('public."GuiaInspeccionItem"')::text g`;return Boolean(r[0]?.d&&r[0]?.g)}
export async function subirProyecto(fd:FormData){const u=await actor(),id=t(fd,"inspeccionId"),tipo=t(fd,"tipo"),archivo=fd.get("archivo");if(!(await tablas()))volver(id,"error","La preparación técnica requiere aplicar primero su migración en preproducción.");if(!TIPOS.has(tipo))volver(id,"error","Tipo de proyecto inválido.");if(!(archivo instanceof File)||archivo.size===0)volver(id,"error","Selecciona un PDF.");if(archivo.type!=="application/pdf")volver(id,"error","Solo se permiten archivos PDF.");if(archivo.size>25*1024*1024)volver(id,"error","El PDF no puede exceder 25 MB.");const ins=await prisma.inspeccion.findUnique({where:{id},select:{id:true,estado:true}});if(!ins)volver(id,"error","La inspección no existe.");if(ins.estado!=="PROGRAMADA")volver(id,"error","Los proyectos deben cargarse antes de iniciar la inspección.");const docId=randomUUID(),ruta=`${id}/proyectos/${tipo.toLowerCase()}-${docId}.pdf`,bucket=process.env.SUPABASE_PROYECTOS_BUCKET||"proyectos-inspeccion";const bytes=Buffer.from(await archivo.arrayBuffer());const {error}=await supabaseAdmin.storage.from(bucket).upload(ruta,bytes,{contentType:"application/pdf",upsert:false});if(error)volver(id,"error",`No fue posible guardar el PDF: ${error.message}`);try{await prisma.$transaction(async tx=>{await tx.$executeRaw`INSERT INTO "DocumentoProyectoInspeccion" ("id","inspeccionId","tipo","nombreOriginal","bucket","ruta","mimeType","bytes","subidoPorId") VALUES (${docId},${id},${tipo},${archivo.name},${bucket},${ruta},'application/pdf',${archivo.size},${u.id})`;const existentes=await tx.$queryRaw<Array<{n:number}>>`SELECT COUNT(*)::int n FROM "GuiaInspeccionItem" WHERE "inspeccionId"=${id} AND "tipoProyecto"=${tipo}`;if(Number(existentes[0]?.n??0)===0){let orden=100;for(const concepto of BASE[tipo]??BASE.OTROS){await tx.$executeRaw`INSERT INTO "GuiaInspeccionItem" ("id","inspeccionId","origen","tipoProyecto","area","concepto","orden","creadoPorId") VALUES (${randomUUID()},${id},'PROYECTO',${tipo},${tipo.replaceAll('_',' ')},${concepto},${orden++},${u.id})`;}}});}catch(e){await supabaseAdmin.storage.from(bucket).remove([ruta]);throw e}await registrarAuditoria({tipo:TipoEvento.EDITAR,entidad:"DocumentoProyectoInspeccion",entidadId:docId,inspeccionId:id,usuarioId:u.id,descripcion:`${u.rol} cargó proyecto ${tipo}: ${archivo.name}.`});revalidatePath(`/panel/inspecciones/${id}/preparacion`);volver(id,"ok","Proyecto cargado y agregado a la guía técnica.")}
export async function agregarItemManual(fd:FormData){const u=await actor(),id=t(fd,"inspeccionId"),area=t(fd,"area"),concepto=t(fd,"concepto"),especificacion=t(fd,"especificacion")||null;if(!(await tablas()))volver(id,"error","La preparación técnica aún no está habilitada en esta base de datos.");if(!area||!concepto)volver(id,"error","Área y concepto son obligatorios.");await prisma.$executeRaw`INSERT INTO "GuiaInspeccionItem" ("id","inspeccionId","origen","area","concepto","especificacion","orden","creadoPorId") VALUES (${randomUUID()},${id},'MANUAL',${area},${concepto},${especificacion},9999,${u.id})`;await registrarAuditoria({tipo:TipoEvento.EDITAR,entidad:"GuiaInspeccionItem",inspeccionId:id,usuarioId:u.id,descripcion:`${u.rol} agregó manualmente a la guía: ${area} / ${concepto}.`});revalidatePath(`/panel/inspecciones/${id}/preparacion`);volver(id,"ok","Concepto agregado a la guía.")}
